Repository ugent-library/biblio-backoffice, pull requests merged in 2024-06, with the labels that each got.

#1603 Nil reference bugfix in dataset project list when EUProject is nil
  views/dataset/projects.templ
  views/dataset/projects_templ.go
  views/publication/projects.templ
  views/publication/projects_templ.go
Labels: bug

#1618 Fix for Tagify save after typing
  assets/js/ui/tags.js
  cypress/e2e/datasets/edit/biblio-messages.cy.ts
  cypress/e2e/datasets/edit/description.cy.ts
  cypress/e2e/issues/issue-1617.cy.ts
  cypress/e2e/publications/edit/biblio-messages.cy.ts
  cypress/e2e/publications/edit/description.cy.ts
  cypress/support/commands/set-field.ts
  package-lock.json
  package.json
  static/js/app-7OLZPKO6.js
  static/js/app-7OLZPKO6.js.LEGAL.txt
  static/js/app-7OLZPKO6.js.map
  static/js/app-JT7MYF32.js
  static/js/app-JT7MYF32.js.map
  static/manifest.json
  views/form/form.templ
  views/form/form_templ.go
Labels: cypress-tested

#1635 Fix biblio message links not showing for publications in activity tab
  CHANGELOG.md
  views/publication/activity.templ
  views/publication/activity_templ.go
Labels: cypress-test-requested
