Repository ugent-library/biblio-backoffice, pull requests merged in 2024-05, with the labels that each got.

#1476 Added URLBuilder for constructing outgoing url's
  views/pagination.templ
  views/pagination_templ.go
  views/urls.go
  views/urls_test.go
Labels: refactor

#1474 Added dataset project fixes #1402
  views/dataset/suggest_projects.templ
  views/dataset/suggest_projects_templ.go
  views/urls.go
  views/urls_test.go
Labels: refactor

#1473 Refactored add/suggest publication project popup to templ #1402
  handlers/publicationediting/project.go
  routes/register.go
  views/publication/_suggest_projects.gohtml
  views/publication/add_project.gohtml
  views/publication/add_project.templ
  views/publication/add_project_templ.go
  views/publication/suggest_projects.templ
  views/publication/suggest_projects_templ.go
Labels: refactor

#1475 Refactor to templ/datasets
  ctx/ctx.go
  handlers/datasetsearching/handler.go
  handlers/datasetsearching/search.go
  routes/register.go
  views/candidaterecord/list.templ
  views/candidaterecord/list_templ.go
  views/contributor/summary.templ
  views/contributor/summary_templ.go
  views/dataset/pages/search.gohtml
  views/dataset/search.templ
  views/dataset/search_hit.gohtml
  views/dataset/search_hit.templ
  views/dataset/search_hit_templ.go
  views/dataset/search_templ.go
  views/dataset/status.templ
  views/dataset/status_templ.go
  views/dataset/summary.templ
  views/dataset/summary_templ.go
  views/helpers.templ
  views/helpers_templ.go
  views/pagination.templ
  views/pagination_templ.go
  views/publication/summary.templ
  views/publication/summary_templ.go
  views/record_timestamp.go
  views/relatedorganization/summary.templ
  views/relatedorganization/summary_templ.go
  views/search.templ
  views/search_templ.go
  views/urls.go
  views/urls_test.go
Labels: refactor

#1515 do not translate values of facet reviewer_tags
  views/dataset/search.templ
  views/dataset/search_templ.go
Labels: bug

#1506 Refactor publication details form; make templ form components
  handlers/publicationediting/details.go
  localize/localize.go
  routes/register.go
  views/form/form.templ
  views/form/form_templ.go
  views/publication/details.templ
  views/publication/details_templ.go
  views/publication/edit_details.templ
  views/publication/edit_details_templ.go
  views/replace.templ
  views/replace_templ.go
Labels: refactor

#1534 Refactor publication edit lay summary
  handlers/publicationediting/lay_summary.go
  routes/register.go
  views/publication/add_lay_summary.gohtml
  views/publication/edit_lay_summary.gohtml
  views/publication/edit_lay_summary.templ
  views/publication/edit_lay_summary_templ.go
  views/publication/lay_summaries.templ
  views/publication/lay_summaries_templ.go
  views/publication/refresh_lay_summaries.gohtml
Labels: refactor

#1525 Refactor publication edit conference and change type
  handlers/publicationediting/conference.go
  handlers/publicationediting/details.go
  handlers/publicationediting/type.go
  routes/register.go
  views/publication/conference.templ
  views/publication/conference_templ.go
  views/publication/edit_conference.gohtml
  views/publication/edit_conference.templ
  views/publication/edit_conference_templ.go
  views/publication/refresh_conference.gohtml
  views/publication/refresh_details.gohtml
Labels: refactor

#1537 Refactor dataset activity
  cypress/e2e/issues/issue-0844.cy.ts
  cypress/e2e/issues/issue-1237.cy.ts
  cypress/e2e/issues/issue-1402.cy.ts
  cypress/e2e/publications/import-bibtex.cy.ts
  cypress/e2e/publications/import-identifier.cy.ts
  cypress/e2e/publications/import-wos.cy.ts
  cypress/e2e/routing.cy.ts
  cypress/support/commands/trigger-htmx.ts
  cypress/support/e2e.ts
  cypress/support/typings.d.ts
  handlers/datasetediting/activity.go
  routes/register.go
  views/dataset/_reviewer_note_body.gohtml
  views/dataset/_reviewer_tags_body.gohtml
  views/dataset/activity.templ
  views/dataset/activity_templ.go
  views/dataset/edit_message.gohtml
  views/dataset/edit_message.templ
  views/dataset/edit_message_templ.go
  views/dataset/edit_reviewer_note.gohtml
  views/dataset/edit_reviewer_note.templ
  views/dataset/edit_reviewer_note_templ.go
  views/dataset/edit_reviewer_tags.gohtml
  views/dataset/edit_reviewer_tags.templ
  views/dataset/edit_reviewer_tags_templ.go
  views/dataset/refresh_message.gohtml
  views/dataset/refresh_reviewer_note.gohtml
  views/dataset/refresh_reviewer_tags.gohtml
Labels: refactor

#1546 Converted dataset add/edit abstract views to Templ #1536
  handlers/datasetediting/abstract.go
  routes/register.go
  views/dataset/abstracts.templ
  views/dataset/abstracts_templ.go
  views/dataset/add_abstract.gohtml
  views/dataset/edit_abstract.gohtml
  views/dataset/edit_abstract.templ
  views/dataset/edit_abstract_templ.go
  views/dataset/refresh_abstracts.gohtml
Labels: refactor

#1549 Refactor to templ/datasetediting edit link
  handlers/datasetediting/link.go
  routes/register.go
  views/dataset/_links_body.gohtml
  views/dataset/_show_links.gohtml
  views/dataset/add_link.gohtml
  views/dataset/add_link.templ
  views/dataset/add_link_templ.go
  views/dataset/edit_link.gohtml
  views/dataset/edit_link.templ
  views/dataset/edit_link_templ.go
  views/dataset/link_form.templ
  views/dataset/link_form_templ.go
  views/dataset/refresh_links.gohtml
  views/dataset/show_description.gohtml
Labels: refactor

#1552 Convert publication activity forms to Templ
  cypress/e2e/issues/issue-0844.cy.ts
  cypress/e2e/issues/issue-1402.cy.ts
  cypress/e2e/routing.cy.ts
  handlers/publicationediting/activity.go
  routes/register.go
  views/publication/_message_body.gohtml
  views/publication/_reviewer_note_body.gohtml
  views/publication/_reviewer_tags_body.gohtml
  views/publication/activity.templ
  views/publication/activity_templ.go
  views/publication/edit_message.gohtml
  views/publication/edit_message.templ
  views/publication/edit_message_templ.go
  views/publication/edit_reviewer_note.gohtml
  views/publication/edit_reviewer_note.templ
  views/publication/edit_reviewer_note_templ.go
  views/publication/edit_reviewer_tags.gohtml
  views/publication/edit_reviewer_tags.templ
  views/publication/edit_reviewer_tags_templ.go
  views/publication/refresh_message.gohtml
  views/publication/refresh_reviewer_note.gohtml
  views/publication/refresh_reviewer_tags.gohtml
Labels: refactor

#1557 Converted create and delete dataset department to Templ
  handlers/datasetediting/department.go
  routes/register.go
  views/dataset/_departments_body.gohtml
  views/dataset/contributors.templ
  views/dataset/contributors_templ.go
  views/dataset/refresh_departments.gohtml
Labels: refactor

#1561 refactor to templ - dataset edit contributors
  handlers/datasetediting/contributors.go
  handlers/datasetediting/handler.go
  routes/register.go
  views/add_impersonation_suggest.templ
  views/add_impersonation_suggest_templ.go
  views/contributor/suggest_summary.templ
  views/contributor/suggest_summary_templ.go
  views/contributor/summary.templ
  views/contributor/summary_templ.go
  views/dataset/_add_contributor_suggest.gohtml
  views/dataset/_add_next_contributor.gohtml
  views/dataset/_contributors_body.gohtml
  views/dataset/_contributors_columns.gohtml
  views/dataset/_edit_contributor_suggest.gohtml
  views/dataset/_edit_next_contributor.gohtml
  views/dataset/add_contributor.gohtml
  views/dataset/add_contributor.templ
  views/dataset/add_contributor_suggest.templ
  views/dataset/add_contributor_suggest_templ.go
  views/dataset/add_contributor_templ.go
  views/dataset/confirm_create_contributor.gohtml
  views/dataset/confirm_create_contributor.templ
  views/dataset/confirm_create_contributor_templ.go
  views/dataset/confirm_update_contributor.gohtml
  views/dataset/confirm_update_contributor.templ
  views/dataset/confirm_update_contributor_templ.go
  views/dataset/contributor_suggest_form.templ
  views/dataset/contributor_suggest_form_templ.go
  views/dataset/edit_contributor.gohtml
  views/dataset/edit_contributor.templ
  views/dataset/edit_contributor_suggest.templ
  views/dataset/edit_contributor_suggest_templ.go
  views/dataset/edit_contributor_templ.go
  views/dataset/refresh_contributors.gohtml
  views/helpers.templ
  views/helpers_templ.go
  views/replace.templ
  views/replace_templ.go
Labels: refactor

#1555 Convert form errors dialog implementations
  handlers/datasetcreating/import.go
  handlers/datasetediting/contributors.go
  handlers/datasetediting/lock.go
  handlers/datasetediting/publish.go
  handlers/datasetediting/republish.go
  handlers/datasetediting/withdraw.go
  handlers/publicationcreating/import.go
  handlers/publicationediting/contributors.go
  handlers/publicationediting/lock.go
  handlers/publicationediting/publish.go
  handlers/publicationediting/republish.go
  handlers/publicationediting/withdraw.go
  routes/register.go
  views/dataset/pages/add_identifier.templ
  views/dataset/pages/add_identifier_templ.go
  views/form_errors_dialog.gohtml
  views/form_errors_dialog.templ
  views/form_errors_dialog_templ.go
  views/publication/pages/add_identifier.templ
  views/publication/pages/add_identifier_templ.go
Labels: refactor

#1570 Refactor to templ: lock/unlock should redirect to dataset detail page, not dataset search page
  views/dataset/show.templ
  views/dataset/show_templ.go
Labels: bug, refactor
